// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swgjfcicvaxedtvlqisd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3Z2pmY2ljdmF4ZWR0dmxxaXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MTI4MzQsImV4cCI6MjA1MDM4ODgzNH0.WXUQokoHAr-W8u9dK5_FWc440b242yiBrxVMJa9YgSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);